apiVersion: apps/v1
kind: Deployment
metadata:  
  name: rocket-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rocket
  template:
    metadata:
      labels:
        app: rocket
    spec:
      containers:
        -  name: anand-container
           image: anandhakumarg/rocket-image:9
           ports:
             -  containerPort: 80
           imagePullSecrets:
             - name: my-docker-secret
          
  
